# @format

name: GitHub Classroom Workflow

on:
  push:
    branches:
      - gh-pages
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: install pkg
        run: |
          npm install yarn -g
          yarn install
      - name: get csv
        uses: ./src/scripts/csv
      - name: create env file
        run: |
          echo AUTH=${{ secrets.ACTION_ACCESS }} >> ./src/scripts/parse/.env
          echo ORG=${{ secrets.ORG }} >> ./src/scripts/parse/.env
      - name: csv to json
        uses: ./src/scripts/parse
      - name: build pages
        run: yarn build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: gh-pages-action
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
